name: CI

on:
  push:
    branches:
      - dev

jobs:
  setup-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        os: [ubuntu-latest, macos-latest, windows-latest]

      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.3.0

      - name: Set up Python (${{ matrix.python-version }}) for ${{ matrix.os }}
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install library dependencies
        run: |
          python -m pip install -Ur requirements.txt

      - name: Install library
        run: python -m pip install -e .

      - name: Run tests
        run: |
          pytest --cov=src --cov-report=term-missing -vv -s tests
